### ISSUE TITLE
Right definition of sqrtDm

### ISSUE THREAD

**Issue by moiseszeleny** [earlyuniverse/ulysses#2]
Hi, I am reading the code of the ulsbase.py, and I am confused with the definition of sqrtDm. Then I would like to ask you some questions. 
 - Are m11, m22 and m33 the light neutrino masses?
 -  The definitions for m22 is: `m22 = np.sqrt(np.sqrt( self.msplit2_solar + self.m*self.m))`, and the m33 definition is analogous, but I think the right definition should be `m22 = np.sqrt( self.msplit2_solar + self.m*self.m)` with only one sqrt operation. Is this right?
Thanks in advance.

**Comment by jturner90** [comment]
Hi and thanks for your interest. This should be line 283? This is defining the square root of the light neutrino mass matrix, which is needed for the Casas Ibarra parametrisation of the Yukawa matrix. See for example, Eq (3) of the manual: https://arxiv.org/pdf/2007.09150.pdf. i.e. we need the square root of the mass matrix to get the Yukawa. That is why the square root is taken twice.

**Comment by moiseszeleny** [comment]
Ok. I got it thanks
