### ISSUE TITLE
Runing uls-scan

### ISSUE THREAD

**Issue by bulgaa8** [earlyuniverse/ulysses#9]
I am trying to run the command: uls−scan −m 1BE1F_PBH examples /PBH.dat −o PBHscan .pdf
But I have some error message as follows.

Traceback (most recent call last):
  File "/home/user/.local/bin/uls-scan", line 87, in <module>
    assert(len(RNG)==1)
AssertionError

How can I handle this error? Thank in advance.

**Comment by jturner90** [comment]
Hi there, sorry for the late reply. 

Yes, you will need to make a range in the examples /PBH.dat file. It is a fixed point and so nothing is varying. If you modify, for example, aPBHi 0.0 --> aPBHi 0.0 1.0 it will run. 

I will clarify this in the manual. Thanks for noting this.
